<?php

namespace sambuh_2;
use Illuminate\Database\Seeder;

class GoalTemplatesTableSeeder extends Seeder
{
    public function run()
    {
        $goalTemplates = collect([
            (object) [
                'name'              => 'Ta hand om sin hälsa',
                'description'       => 'Mål att självständigt uppsöka och ta del av vårdinsatser.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Hälsa')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Hälsobefrämjande rutiner',
                'description'       => 'Mål att skapa rutiner för att må bättre fysiskt och psykiskt',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Hälsa')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Psykologkontakt',
                'description'       => 'Mål att ha en pågående psykologkontakt.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Hälsa')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Matrutiner',
                'description'       => 'Mål att ha fasta regelbundna rutiner kring mat.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Hälsa')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Träning/motion',
                'description'       => 'Mål att regelbundet upprätthålla någon form av träning/motion.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Hälsa')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Kunna ta myndighetskontakter',
                'description'       => 'Mål att ____ ska kunna ta kontakt med myndigheter och liknande för att kunna leva självständigt.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Klara sig själv')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Vardagsrutiner',
                'description'       => 'Mål att skaffa rutiner som möjliggör en fungerande vardag.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Klara sig själv')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Myndighetskontakter',
                'description'       => 'Mål att bli trygg i att ta kontakt med myndigheter.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Klara sig själv')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Övningsköra med Sambuh',
                'description'       => 'Mål att skriva in sig på körskola och slutföra fem lektioner för att kunna övningsköra med Sambuh.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Klara sig själv')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Få ett arbete',
                'description'       => 'Mål att aktivt söka och få någon typ av anställning.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Sysselsättning')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Aktiv fritid',
                'description'       => 'Mål att ha en regelbunden fritidsaktivitet.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Hälsa')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Hantera ångest',
                'description'       => 'Mål att hitta strategier för att hantera ångest.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Hälsa')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Drogfrihet',
                'description'       => 'Mål att under en längre tid vara drogfri.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Hälsa')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Sömnrutiner',
                'description'       => 'Mål att ha bra rutiner kring sömn.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Hälsa')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Självständig i boende',
                'description'       => 'Mål att ___ självständigt ska klara av att sköta sitt boende.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Klara sig själv')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Boendereferens',
                'description'       => 'Mål att få en boendereferens från Sambuh.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Klara sig själv')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Egen ekonomi',
                'description'       => 'Mål att hantera sin vardagsekonomi vad gäller hyra, räkningar, försäkringar, deklaration och liknande.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Klara sig själv')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Ekonomiska svårigheter',
                'description'       => 'Mål att få kontroll över sin ekonomi och bli av med ekonomiska svårigheter.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Klara sig själv')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Söka bostad',
                'description'       => 'Mål att hitta ett boende efter referensperioden.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Klara sig själv')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Fungerande skolgång',
                'description'       => 'Mål att din skolgång fungerar avseende rutiner och närvaro.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Sysselsättning')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Regelbunden praktik',
                'description'       => 'Mål att hitta en praktik och praktisera under en längre period.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Sysselsättning')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Sysselsättning',
                'description'       => 'Mål att hitta en utbildning som passar med den plan som finns gällande arbete eller studier.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Sysselsättning')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Läsa in gymnasiebetyg',
                'description'       => 'Mål att läsa in resterande betyg för att få en gymnasieexamen.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Sysselsättning')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Läsa in grundskolebetyg',
                'description'       => 'Mål att få betyg för att kunna påbörja en gymnasieutbildning.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Sysselsättning')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Sommarjobb',
                'description'       => 'Mål att få en anställning inför sommaren.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Sysselsättning')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Efter examen',
                'description'       => 'Mål att planera sin sysselsättning efter gymnasieexamen.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Sysselsättning')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Relation till förälder/föräldrar',
                'description'       => 'Mål att hitta en fungerande relation till sin förälder/föräldrar.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Familj och sociala relationer')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Kontakt med syskon',
                'description'       => 'Mål att få en fungerande kontakt med syskon.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Familj och sociala relationer')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Positiva kompisrelationer',
                'description'       => 'Mål att hitta eller behålla positiva kompisrelationer.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Familj och sociala relationer')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Positivt nätverk',
                'description'       => 'Mål att ha ett positivt nätverk runt sig.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Familj och sociala relationer')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Ta ansvar för kontakter',
                'description'       => 'Mål att ta eget ansvar för kontakter med myndigheter och andra professionella.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Familj och sociala relationer')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Bryta med negativa relationer',
                'description'       => 'Mål att bryta med relationer som påverkar negativt.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Familj och sociala relationer')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Hantera brutna relationer',
                'description'       => 'Mål att hitta ett sätt att kunna gå vidare med sin historia av brutna relationer.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Familj och sociala relationer')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Hantera känslor',
                'description'       => 'Mål att tillgodogöra sig verktyg för att hantera känslor.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Personlig utveckling')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Trygghet',
                'description'       => 'Mål att känna sig trygg i sitt boende.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Personlig utveckling')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Självförtroende',
                'description'       => 'Mål att känna att utveckling skett gällande självförtroende.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Personlig utveckling')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Känna tillit',
                'description'       => 'Mål att känna en högre grad av tillit till andra människor.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Personlig utveckling')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Trygghet i sig själv',
                'description'       => 'Mål att känna trygghet i att uttrycka det jag känner och tänker.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Personlig utveckling')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Be om hjälp',
                'description'       => 'Mål att känna trygghet att kunna be andra personer om hjälp.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Personlig utveckling')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Hantera konflikter',
                'description'       => 'Mål att hitta bra och användbara strategier för att hantera konflikter.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Personlig utveckling')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            (object) [
                'name'              => 'Trygghet i offentlighet',
                'description'       => 'Mål att känna trygghet i att agera och vara synlig i offentliga sammanhang.',
                'start_at'          => null,
                'end_at'            => null,
                'color'             => null,
                'goal_category_id'  => \App\GoalCategory::where('name', 'Personlig utveckling')->firstOrFail()->id,
                'goal_status_id'    => \App\GoalStatus::where('name', 'Nytt')->firstOrFail()->id,
            ],
            
        ]);

        \App\GoalTemplate::get()->each(function ($f) {
            $f->delete();
        });

        $goalTemplates->each(function ($f) {
            \App\GoalTemplate::create([
                'name'              => $f->name,
                'description'       => $f->description,
                'start_at'          => $f->start_at,
                'end_at'            => $f->end_at,
                'goal_category_id'  => $f->goal_category_id,
                'goal_status_id'    => $f->goal_status_id,
            ]);
        });
    }
}
